version: "3.8"

services:
  app1:
    build: .
    environment:
      - APP_NAME=App1

  app2:
    build: .
    environment:
      - APP_NAME=App2

  app3:
    build: .
    environment:
      - APP_NAME=App3

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Custom NGINX config file
    ports:
      - "8080:8080" # Expose port 8080 for the proxy server
    depends_on:
      - app1
      - app2
      - app3
